"""
Django settings for homelab_dashboard project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-change-this-in-production-123456789')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'homelab_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homelab_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use SQLite for development (DEBUG=True) and configurable database for production
if DEBUG:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Production: Use environment variables
    # Supports DATABASE_URL or individual connection parameters
    DATABASE_URL = os.environ.get('DATABASE_URL')
    
    if DATABASE_URL:
        # Parse DATABASE_URL (format: postgres://user:password@host:port/dbname)
        import re
        pattern = r'(\w+)://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)'
        match = re.match(pattern, DATABASE_URL)
        
        if match:
            engine_map = {
                'postgres': 'django.db.backends.postgresql',
                'postgresql': 'django.db.backends.postgresql',
                'mysql': 'django.db.backends.mysql',
                'sqlite': 'django.db.backends.sqlite3',
            }
            
            db_engine = match.group(1)
            DATABASES = {
                'default': {
                    'ENGINE': engine_map.get(db_engine, 'django.db.backends.postgresql'),
                    'NAME': match.group(6),
                    'USER': match.group(2),
                    'PASSWORD': match.group(3),
                    'HOST': match.group(4),
                    'PORT': match.group(5),
                }
            }
        else:
            # Fallback to SQLite if URL parsing fails
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
    else:
        # Use individual environment variables
        DATABASES = {
            'default': {
                'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
                'NAME': os.environ.get('DB_NAME', 'homelab_dashboard'),
                'USER': os.environ.get('DB_USER', 'postgres'),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'HOST': os.environ.get('DB_HOST', 'localhost'),
                'PORT': os.environ.get('DB_PORT', '5432'),
            }
        }
        
        # Add connection options for PostgreSQL
        if 'postgresql' in DATABASES['default']['ENGINE']:
            DATABASES['default']['OPTIONS'] = {
                'connect_timeout': 10,
            }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Traefik API Configuration (Optional - Auto-detected)
# If Traefik API URL is set and responding, services will be auto-discovered.
# If not configured or not responding, the app automatically uses manual service management.
# Leave TRAEFIK_API_URL empty or unset to use manual-only mode.
TRAEFIK_API_URL = os.environ.get('TRAEFIK_API_URL', '')
TRAEFIK_API_USERNAME = os.environ.get('TRAEFIK_API_USERNAME', '')
TRAEFIK_API_PASSWORD = os.environ.get('TRAEFIK_API_PASSWORD', '')

# Service refresh interval in seconds
SERVICE_REFRESH_INTERVAL = int(os.environ.get('SERVICE_REFRESH_INTERVAL', '60'))

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'dashboard': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Field Encryption Key
# Automatically generate and persist encryption key
def get_or_create_encryption_key():
    """Get existing encryption key or generate a new one."""
    key_file = BASE_DIR / '.encryption_key'
    
    # Try to load existing key
    if key_file.exists():
        try:
            with open(key_file, 'r') as f:
                key = f.read().strip()
                if key:
                    return key
        except Exception as e:
            import warnings
            warnings.warn(f"Could not read encryption key file: {e}", RuntimeWarning)
    
    # Generate new key if file doesn't exist or is empty
    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode()
    
    # Save the key for future use
    try:
        with open(key_file, 'w') as f:
            f.write(key)
        # Set restrictive permissions (owner read/write only)
        import os
        os.chmod(key_file, 0o600)
        
        if DEBUG:
            import warnings
            warnings.warn(
                f"Generated new encryption key and saved to {key_file}. "
                "Keep this file secure and backed up!",
                RuntimeWarning
            )
    except Exception as e:
        import warnings
        warnings.warn(f"Could not save encryption key to file: {e}", RuntimeWarning)
    
    return key

FIELD_ENCRYPTION_KEY = get_or_create_encryption_key()


# ============================================================
# Media Discovery Feed Settings
# ============================================================

# TMDb (The Movie Database) — movies and TV shows
TMDB_API_KEY = os.environ.get('TMDB_API_KEY', '')

# Radarr — movie library management
RADARR_URL = os.environ.get('RADARR_URL', '').rstrip('/')
RADARR_API_KEY = os.environ.get('RADARR_API_KEY', '')

# Sonarr — TV/anime library management
SONARR_URL = os.environ.get('SONARR_URL', '').rstrip('/')
SONARR_API_KEY = os.environ.get('SONARR_API_KEY', '')

# MyAnimeList supplementary anime data (optional)
MAL_CLIENT_ID = os.environ.get('MAL_CLIENT_ID', '')

# Cache TTL for external feed results (TMDb / AniList / MAL): default 6 hours
MEDIA_FEED_CACHE_TTL = int(os.environ.get('MEDIA_FEED_CACHE_TTL', '21600'))

# Cache TTL for Radarr/Sonarr library IDs: default 15 minutes
MEDIA_LIBRARY_CACHE_TTL = int(os.environ.get('MEDIA_LIBRARY_CACHE_TTL', '900'))

# In-memory cache — only set if not already configured by deployment
if 'CACHES' not in locals():
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
