# Generated by Django 5.1.4 on 2025-12-25 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('service_type', models.CharField(choices=[('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('vm', 'Virtual Machine'), ('bare_metal', 'Bare Metal'), ('other', 'Other')], default='docker', max_length=50)),
                ('provider', models.CharField(default='traefik', max_length=100)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('uptime_percentage', models.FloatField(blank=True, null=True)),
                ('response_time', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('traefik_router_name', models.CharField(blank=True, max_length=255)),
                ('traefik_service_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='dashboard.service')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
