# Generated by Django 5.1.4 on 2025-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the status last changed', null=True),
        ),
    ]
