# Generated by Django 5.1.4 on 2025-12-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_encrypted_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_detected',
            field=models.BooleanField(default=False, help_text='Whether API was automatically detected'),
        ),
        migrations.AddField(
            model_name='service',
            name='api_endpoint',
            field=models.CharField(blank=True, help_text='Detected API endpoint path', max_length=255),
        ),
    ]
