# Generated by Django 5.1.4 on 2025-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_service_api_detected_service_api_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_last_detected',
            field=models.DateTimeField(blank=True, help_text='When API was last detected/verified', null=True),
        ),
    ]
