# Generated by Django 5.1.4 on 2025-12-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_service_api_last_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Whether service was added manually or auto-discovered'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.CharField(choices=[('traefik', 'Traefik'), ('manual', 'Manual'), ('external', 'External')], default='traefik', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('vm', 'Virtual Machine'), ('bare_metal', 'Bare Metal'), ('external', 'External Service'), ('other', 'Other')], default='docker', max_length=50),
        ),
    ]
