# Generated by Django 5.1.4 on 2025-12-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_service_is_manual_alter_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_detection_attempts',
            field=models.IntegerField(default=0, help_text='Number of failed API detection attempts'),
        ),
        migrations.AddField(
            model_name='service',
            name='api_next_check',
            field=models.DateTimeField(blank=True, help_text='When to retry API detection next', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.CharField(choices=[('traefik', 'Traefik'), ('local', 'Local'), ('external', 'External')], default='traefik', max_length=100),
        ),
    ]
