# Generated by Django 5.1.4 on 2025-12-25 23:16

import dashboard.utils.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_api_detection_throttling'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title for the panel', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this panel shows')),
                ('grafana_url', models.URLField(help_text='Base URL of your Grafana instance (e.g., https://grafana.example.com)', max_length=500)),
                ('dashboard_uid', models.CharField(help_text='Dashboard UID from Grafana (found in dashboard URL)', max_length=255)),
                ('panel_id', models.IntegerField(help_text='Panel ID to embed (found in panel share link)')),
                ('width', models.IntegerField(default=450, help_text='Width in pixels for the embedded panel')),
                ('height', models.IntegerField(default=200, help_text='Height in pixels for the embedded panel')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', help_text='Grafana panel theme', max_length=10)),
                ('refresh', models.CharField(choices=[('5s', '5 seconds'), ('10s', '10 seconds'), ('30s', '30 seconds'), ('1m', '1 minute'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('2h', '2 hours'), ('1d', '1 day')], default='1m', help_text='Auto-refresh interval', max_length=10)),
                ('from_time', models.CharField(default='now-6h', help_text='Start time (e.g., now-6h, now-24h, now-7d)', max_length=50)),
                ('to_time', models.CharField(default='now', help_text='End time (usually "now")', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show this panel on the dashboard')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which panels are displayed (lower numbers first)')),
                ('api_key', dashboard.utils.encryption.EncryptedTextField(blank=True, help_text='Grafana API key if authentication is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, help_text='Optionally link this panel to a specific service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grafana_panels', to='dashboard.service')),
            ],
            options={
                'verbose_name': 'Grafana Panel',
                'verbose_name_plural': 'Grafana Panels',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
